apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-net
  namespace: fastapi
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: mobile-net
  template:
    metadata:
      labels:
        app: mobile-net
    spec:
      containers:
        - name: mobile-net
          image: paidjkim/fastapi:main
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: mobile-net
  namespace: fastapi
  labels:
    app: mobile-net
spec:
  type: NodePort
  selector:
    app: mobile-net
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000