apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-net
  namespace: fastapi
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: mobile-net
  template:
    metadata:
      labels:
        app: mobile-net
    spec:
      containers:
        - name: mobile-net
          image: paidjkim/fastapi:main
          ports:
            - containerPort: 8000